// Auto-generated by: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/supabase/types.ts
// Run this after setting up your Supabase project and running the schema SQL.
// For now, we define a minimal type scaffold that matches the schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type HabitFrequency = 'daily' | 'weekly' | 'custom'
export type HabitDifficulty = 'easy' | 'medium' | 'hard' | 'legendary'
export type HabitCategory =
  | 'fitness' | 'nutrition' | 'sleep' | 'mindfulness'
  | 'learning' | 'creativity' | 'social' | 'productivity'
  | 'finance' | 'hygiene' | 'nature' | 'custom'
export type QuestType = 'daily' | 'weekly' | 'seasonal' | 'one_time'
export type PartyRole = 'owner' | 'admin' | 'member'
export type Mood = 'awful' | 'bad' | 'neutral' | 'good' | 'great'
export type AchievementCategory =
  | 'streak' | 'completion' | 'social' | 'exploration' | 'level' | 'special' | 'seasonal'
export type CosmeticType = 'hat' | 'cape' | 'pet' | 'background' | 'frame' | 'emote'

// Row types (standalone to avoid circular references)
export type ProfileRow = {
  id: string
  username: string
  display_name: string
  avatar_url: string | null
  bio: string
  identity_statement: string
  xp: number
  level: number
  total_habits_completed: number
  active_hat: string | null
  active_cape: string | null
  active_pet: string | null
  active_background: string | null
  active_frame: string | null
  avatar_skin_tone: string
  avatar_hair_style: string
  avatar_hair_color: string
  avatar_outfit: string
  timezone: string
  notifications_enabled: boolean
  sound_enabled: boolean
  public_profile: boolean
  show_on_leaderboard: boolean
  onboarding_completed: boolean
  onboarding_step: number
  created_at: string
  updated_at: string
  last_active_at: string
}

export type HabitRow = {
  id: string
  user_id: string
  name: string
  description: string
  category: HabitCategory
  frequency: HabitFrequency
  frequency_days: number[]
  difficulty: HabitDifficulty
  xp_reward: number
  icon: string
  color: string
  grace_days: number
  biome_id: string
  is_archived: boolean
  sort_order: number
  created_at: string
  updated_at: string
}

export type HabitLogRow = {
  id: string
  habit_id: string
  user_id: string
  log_date: string
  completed: boolean
  mood: Mood | null
  note: string
  xp_awarded: number
  streak_at_log: number
  created_at: string
}

export type StreakRow = {
  id: string
  habit_id: string
  user_id: string
  current_streak: number
  longest_streak: number
  grace_days_used: number
  last_grace_date: string | null
  last_completed_date: string | null
  first_completed_date: string | null
  total_completions: number
  updated_at: string
}

export type PartyRow = {
  id: string
  name: string
  description: string
  invite_code: string
  owner_id: string
  max_members: number
  is_public: boolean
  challenge_name: string | null
  challenge_description: string | null
  challenge_start_date: string | null
  challenge_end_date: string | null
  icon: string
  color: string
  created_at: string
  updated_at: string
}

export type PartyMemberRow = {
  party_id: string
  user_id: string
  role: PartyRole
  joined_at: string
  last_seen_at: string
}

export type MessageRow = {
  id: string
  party_id: string
  user_id: string
  content: string
  message_type: string
  metadata: Json
  is_deleted: boolean
  created_at: string
}

export type AchievementRow = {
  id: string
  name: string
  description: string
  icon: string
  category: AchievementCategory
  xp_reward: number
  criteria: Json
  is_secret: boolean
  is_seasonal: boolean
  season_id: string | null
  sort_order: number
  created_at: string
}

export type UserAchievementRow = {
  user_id: string
  achievement_id: string
  earned_at: string
  progress: number
}

export type QuestRow = {
  id: string
  name: string
  description: string
  type: QuestType
  xp_reward: number
  criteria: Json
  icon: string
  day_of_week: number | null
  season_id: string | null
  active_from: string | null
  active_until: string | null
  sort_order: number
  created_at: string
}

export type UserQuestRow = {
  id: string
  user_id: string
  quest_id: string
  assigned_date: string
  progress: number
  target: number
  completed_at: string | null
  xp_claimed: boolean
  created_at: string
}

export type NotificationRow = {
  id: string
  user_id: string
  type: string
  title: string
  body: string
  metadata: Json
  is_read: boolean
  created_at: string
}

export type MapProgressRow = {
  user_id: string
  biome_id: string
  progress_pct: number
  habits_completed: number
  is_unlocked: boolean
  is_completed: boolean
  unlocked_at: string | null
  completed_at: string | null
}

export type CosmeticItemRow = {
  id: string
  name: string
  description: string
  type: CosmeticType
  sprite_key: string
  rarity: string
  xp_cost: number | null
  is_premium: boolean
  unlock_criteria: Json
  created_at: string
}

export type UserCosmeticRow = {
  user_id: string
  cosmetic_id: string
  acquired_at: string
}

export type FriendshipRow = {
  id: string
  requester_id: string
  addressee_id: string
  status: string
  created_at: string
  updated_at: string
}

export type ReactionRow = {
  id: string
  user_id: string
  emoji: string
  target_type: string
  habit_log_id: string | null
  message_id: string | null
  created_at: string
}

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow
        Insert: Partial<ProfileRow> & { id: string }
        Update: Partial<ProfileRow>
        Relationships: {
          foreignKeyName: string
          columns: string[]
          isOneToOne: boolean
          referencedRelation: string
          referencedColumns: string[]
        }[]
      }
      habits: {
        Row: HabitRow
        Insert: Omit<HabitRow, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<HabitRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      habit_logs: {
        Row: HabitLogRow
        Insert: Omit<HabitLogRow, 'id' | 'created_at'>
        Update: Partial<HabitLogRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      streaks: {
        Row: StreakRow
        Insert: Omit<StreakRow, 'id'>
        Update: Partial<StreakRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      parties: {
        Row: PartyRow
        Insert: Omit<PartyRow, 'id' | 'invite_code' | 'created_at' | 'updated_at'>
        Update: Partial<PartyRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      party_members: {
        Row: PartyMemberRow
        Insert: Omit<PartyMemberRow, 'joined_at' | 'last_seen_at'>
        Update: Partial<PartyMemberRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      messages: {
        Row: MessageRow
        Insert: Omit<MessageRow, 'id' | 'created_at'>
        Update: Partial<MessageRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      achievements: {
        Row: AchievementRow
        Insert: Omit<AchievementRow, 'created_at'>
        Update: Partial<AchievementRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      user_achievements: {
        Row: UserAchievementRow
        Insert: Omit<UserAchievementRow, 'earned_at'>
        Update: Partial<UserAchievementRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      quests: {
        Row: QuestRow
        Insert: Omit<QuestRow, 'created_at'>
        Update: Partial<QuestRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      user_quests: {
        Row: UserQuestRow
        Insert: Omit<UserQuestRow, 'id' | 'created_at'>
        Update: Partial<UserQuestRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      notifications: {
        Row: NotificationRow
        Insert: Omit<NotificationRow, 'id' | 'created_at'>
        Update: Partial<NotificationRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      map_progress: {
        Row: MapProgressRow
        Insert: Partial<MapProgressRow> & { user_id: string; biome_id: string }
        Update: Partial<MapProgressRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      cosmetic_items: {
        Row: CosmeticItemRow
        Insert: Omit<CosmeticItemRow, 'created_at'>
        Update: Partial<CosmeticItemRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      user_cosmetics: {
        Row: UserCosmeticRow
        Insert: Omit<UserCosmeticRow, 'acquired_at'>
        Update: Partial<UserCosmeticRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      friendships: {
        Row: FriendshipRow
        Insert: Omit<FriendshipRow, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<FriendshipRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
      reactions: {
        Row: ReactionRow
        Insert: Omit<ReactionRow, 'id' | 'created_at'>
        Update: Partial<ReactionRow>
        Relationships: { foreignKeyName: string; columns: string[]; isOneToOne: boolean; referencedRelation: string; referencedColumns: string[] }[]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      habit_frequency: HabitFrequency
      habit_difficulty: HabitDifficulty
      habit_category: HabitCategory
      quest_type: QuestType
      party_role: PartyRole
      mood: Mood
      cosmetic_type: CosmeticType
    }
    CompositeTypes: Record<string, never>
  }
}
